services:
  gst:
    container_name: itone-ai
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ipc: host
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: /data
        target: /data
      - type: bind
        source: $PWD/legacy
        target: /app/legacy
      - type: bind
        source: $PWD/app
        target: /app/app
      - type: bind
        source: $PWD/tensorrt
        target: /tensorrt
    command: ["uvicorn", "app.main:app", "--port=8000", "--host=0.0.0.0"]
    # command: 
    #   - gunicorn
    #   - main:app
    #   - -b
    #   - 0.0.0.0:8000
    #   - --workers
    #   - '2'
    #   - --worker-class
    #   - 'uvicorn.workers.UvicornWorker'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - TZ=Asia/Seoul
      - DEBIAN_FRONTEND=noninteractive
      - REDIS_HOST=redis
  celery_worker_1:
    container_name: itone-worker
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    command: celery -A legacy.tasks worker -c 12 -n celery0@myhost --loglevel=info
    volumes:
      - type: bind
        source: $PWD/legacy
        target: /app/legacy
      - type: bind
        source: $PWD/app
        target: /app/app
      - type: bind
        source: $PWD/tensorrt
        target: /tensorrt
      - type: bind
        source: /data
        target: /data
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=0 
      - TZ=Asia/Seoul
      - DEBIAN_FRONTEND=noninteractive
      - REDIS_HOST=redis
  celery_beat:
    container_name: itone-beat
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    command: celery -A legacy.tasks beat --loglevel=info
    volumes:
      - type: bind
        source: $PWD/legacy
        target: /app/legacy
      - type: bind
        source: $PWD/app
        target: /app/app
      - type: bind
        source: $PWD/tensorrt
        target: /tensorrt
      - type: bind
        source: /data
        target: /data
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=0 
      - TZ=Asia/Seoul
      - DEBIAN_FRONTEND=noninteractive
      - REDIS_HOST=redis

  redis:
    container_name: itone-redis
    build: 
      context: ./redis
      dockerfile: Dockerfile

  prometheus:
   container_name: prometheus
   image: prom/prometheus
   ports:
     - "1212:9090"
   volumes:
     - ./prometheus/config:/etc/prometheus
   depends_on:
     - gst
   command: # web.enalbe-lifecycle은 api 재시작없이 설정파일들을 reload 할 수 있게 해줌
     - '--web.enable-lifecycle'
     - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
   container_name: grafana
   image: grafana/grafana
   ports:
     - "1555:3000"
   depends_on:
     - prometheus

  flower:  
    image: mher/flower
    container_name: flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - FLOWER_PORT=5555
    ports:  
      - 5555:5555

  node-exporter:  
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    ipc: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - TZ=Asia/Seoul
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    ports:  
      - 9100:9100

  dcgm_exporter:
    image: nvcr.io/nvidia/k8s/dcgm-exporter:2.4.6-2.6.10-ubuntu20.04
    container_name: dcgm-exporter
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    restart: always
    environment:
      - DCGM_EXPORTER_NO_HOSTNAME=1
    cap_add:
      - SYS_ADMIN
    ports:
      - "9400:9400"
  # fileserver:
  #   # restart: always
  #   container_name: fileserver
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8800:80"
  #     - "8801:443"
  #   volumes:
  #     - /data:/usr/share/nginx/html
  #     - /home/worker/web/certs:/etc/nginx/certs
  #   # - type: bind
  #   #   source: /data
  #   #   target: /usr/share/nginx/html
  #   # - type: bind
  #   #   source: ../../web/nginx/certs
  #   #   target: /etc/nginx/certs
  #   environment:
  #     - TZ=Asia/Seoul