apiVersion: v1
kind: Service
metadata:
  name: streaming-api
spec:
  selector:
    app: streaming-api
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
  type: ClusterIP
