"""Gateway 의존성: DB/Kafka 클라이언트 주입."""
# from app.infrastructure.persistence.stream_repository import StreamRepository
# from app.infrastructure.kafka.client import get_producer
# def get_stream_repository(): ...
# def get_kafka_producer(): ...
